<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-01-07T14:11:24 PST" name="Amazon Test Script" finished-at="2021-01-07T14:11:31 PST" duration-ms="7175">
    <groups>
    </groups>
    <test started-at="2021-01-07T14:11:24 PST" name="Amazon Home" finished-at="2021-01-07T14:11:31 PST" duration-ms="7175">
      <class name="sarch.TestSearch">
        <test-method is-config="true" signature="setUp(java.lang.String)[pri:0, instance:sarch.TestSearch@d29f28]" started-at="2021-01-07T14:11:24 PST" name="setUp" finished-at="2021-01-07T14:11:31 PST" duration-ms="6942" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://amazon.com]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="test1()[pri:0, instance:sarch.TestSearch@d29f28]" started-at="2021-01-07T14:11:31 PST" name="test1" finished-at="2021-01-07T14:11:31 PST" duration-ms="135" status="FAIL">
          <exception class="java.sql.SQLNonTransientConnectionException">
            <message>
              <![CDATA[Public Key Retrieval is not allowed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLNonTransientConnectionException: Public Key Retrieval is not allowed
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:836)
at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456)
at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
at datasources.ConnectToSqlDB.connectToSqlDatabase(ConnectToSqlDB.java:34)
at datasources.ConnectToSqlDB.readDataBase(ConnectToSqlDB.java:43)
at datasuply.DataReader.grtItemListFromDB(DataReader.java:13)
at sarch.TestSearch.test1(TestSearch.java:18)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLNonTransientConnectionException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method is-config="true" signature="cleanUp()[pri:0, instance:sarch.TestSearch@d29f28]" started-at="2021-01-07T14:11:31 PST" name="cleanUp" finished-at="2021-01-07T14:11:31 PST" duration-ms="53" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanUp -->
      </class> <!-- sarch.TestSearch -->
    </test> <!-- Amazon Home -->
  </suite> <!-- Amazon Test Script -->
</testng-results>
